### ISSUE TITLE
toggleClass() not working as expected

### ISSUE THREAD

**Issue by xstortionist** [kticka/jquery-outclick#1]
If I click "#left-menu-btn" it should toggleClass but when I use outclick toggleclass no longer works. If I remove the outclick function it works as expected. Perhaps I'm doing something wrong?

`

    // ================================ //
    // Menu Button - Open Left Panel    //
    // ================================ //

    $('button#left-menu-btn').click(function() {

        $('nav.left-menu').toggleClass('menu-visible');

        return false;

    });

    // ================================ //
    // Menu Button - Open Right Panel   //
    // ================================ //

    $('button#right-menu-btn').click(function() {

        $('nav.right-menu').toggleClass('menu-visible');

        return false;

    });

    // ================================ //
    // Clickoutside Hide Menu           //
    // ================================ //

    $('nav.left-menu, nav.right-menu').each(function() {
        $(this).outclick({
            callback: function() {
                $(this).removeClass('menu-visible')
            },
            related: [
                $('nav.left-menu, nav.right-menu')
            ]
        });
    });
`

**Comment by kticka** [comment]
Hello there,

After your mail I decided to refactor whole plugin. It was messy and 
silly :)

Now it is much simplier. You don't need define any relations or smth 
like that. Just use it this way:

$('.navleft-menu, .navright-menu').outclick(function() {
     $(this).removeClass('menu-visible');
});

Tell me if it works. If your need more help, just send me url to your 
project, and I will help you implement this plugin.

Good luck!

**Comment by xstortionist** [comment]
@kticka thank you for the prompt reply. I actually got it working last night after I messaged but I'm going to try it again with the new method you provided here. I'll report back with my findings. Thanks!

**Comment by xstortionist** [comment]
@kticka Hi there, I just gave this a test and I'm receiving a reference error.

"ReferenceError: event is not defined"

Give me a few minutes and I'll upload this to my dev server.

**Comment by xstortionist** [comment]
@kticka 

Here is URL to the site:

http://2bitwebsolutions.com/mobile-framework/

**Comment by kticka** [comment]
Just pushed fix. Update and test it. Waiting for feedback :)

**Comment by xstortionist** [comment]
@kticka no more event is not defined error, thanks for that.

Only issue I have is unlike the old plugin, when I click on element that has jquery function, the outclick function not working.

http://2bitwebsolutions.com/mobile-framework/

For example, if you click the hamburger menu icon at top of page and then click back arrow button on bottom sheet (black bar bottom of page) outclick doesn't seem to work. In the old plugin, this worked as expected.

**Comment by kticka** [comment]
As I can see, when I click on that arrow, it doesn't trigger $(document).on('click') event. This is fundamental event for both versions of plugin. Are you sure that with old versin it worked? Other buttons in footer triggers events fine, just that arrow. Maybe you use [event.stopImmediatePropagation()](http://api.jquery.com/event.stopimmediatepropagation/) somewhere?

**Comment by xstortionist** [comment]
@kticka yes, with old version it worked. Let me revert my changes and I can upload old version so you can see it in action.

No other buttons in the footer currently trigger anything, just the back arrow for now. I not use event.stopimmediatepropogation() anywhere.

**Comment by xstortionist** [comment]
@kticka 

This is what I'm using for the bottomsheet:

jQuery(function() {

    // ================================ //
    // Bottom Sheet                     //
    // ================================ //

    $('.bottom-sheet-btn').click(function() {

        $('.m-bottom-sheet').toggleClass('active');

        return false;
    });

    $('.m-bottom-sheet').outclick(function() {
        $(this).removeClass('active');
    });

});

**Comment by kticka** [comment]
Try remove 'return false;' from first event:

```
$('.bottom-sheet-btn').click(function() {
    $('.m-bottom-sheet').toggleClass('active');
});
```

**Comment by xstortionist** [comment]
Oddly enough, when I remove "return false" it doesn't work at all.

http://2bitwebsolutions.com/mobile-framework/

Click bottom arrow to see.

**Comment by xstortionist** [comment]
@kticka is it possible for you to upload the old version of outclick.js file? I apparently overwrote the backup on my server by mistake.

**Comment by xstortionist** [comment]
n/m, i found it. sorry. I'm going to upload old version shortly.

**Comment by xstortionist** [comment]
Here's the old version:

http://2bitwebsolutions.com/mobile-framework/old-outclick/

You will see that everything works as expected. If you click hamburger menu icon and then click back arrow, the menu hides as expected.

here is the javascript:

    // ================================ //
    // Menu Button - Open Left Panel    //
    // ================================ //

    $('button#left-menu-btn').click(function() {

        $('nav.left-menu').toggleClass('menu-visible');

        $(this).outclick({
            callback: function() {
                $('nav.left-menu').removeClass('menu-visible')
            },
            related: [
                $('nav.left-menu')
            ]
        });

        return false;

    });

    // ================================ //
    // Menu Button - Open Right Panel   //
    // ================================ //

    $('button#right-menu-btn').click(function() {

        $('nav.right-menu').toggleClass('menu-visible');

        $(this).outclick({
            callback: function() {
                $('nav.right-menu').removeClass('menu-visible')
            },
            related: [
                $('nav.right-menu')
            ]
        });

        return false;

    });

// ================================ //
    // Bottom Sheet                     //
    // ================================ //

    $('.bottom-sheet-btn').click(function() {

        $('.m-bottom-sheet').toggleClass('active');

        $(this).outclick({
            callback: function() {
                $('.m-bottom-sheet').removeClass('active')
            },
            related: [
                $('.m-bottom-sheet')
            ]
        });

        return false;
    });

**Comment by kticka** [comment]
Your were right. I was using mouseup event instead click in old version. Just pushed fix. Try it :)

**Comment by xstortionist** [comment]
@kticka I'll give it a go in about 10 minutes and report back. Thanks!

**Comment by xstortionist** [comment]
Almost working like old version. Only issue now is toggleClass() doesn't work as expected.

Click the arrow button on the bottom, that should toggleClass() but it doesn't fire after the shelf appears.

http://2bitwebsolutions.com/mobile-framework/

Perhaps I'm doing something wrong with the plugin?

    $('.bottom-sheet-btn').click(function() {

        $('.m-bottom-sheet').toggleClass('active');

        return false;
    });

    $('.m-bottom-sheet').outclick(function() {
        $(this).removeClass('active');
    });

**Comment by xstortionist** [comment]
also tried without return false, still don't work.

**Comment by xstortionist** [comment]
Oddly enough, this works as expected. Is this how I should be doing it moving forward? Adding outclick to my button selector?

    $('.bottom-sheet-btn').click(function() {

        $('.m-bottom-sheet').toggleClass('active');

        return false;
    });

    $('.bottom-sheet-btn').outclick(function() {
        $('.m-bottom-sheet').removeClass('active');
    });

**Comment by xstortionist** [comment]
Alright, this works 100% to what I am expecting. Seems .each() function does the trick here.

    $('.bottom-sheet-btn').click(function() {

        $('.m-bottom-sheet').toggleClass('active');

        return false;
    });

    $('.m-bottom-sheet').each(function() {
        $(this).outclick(function() {
            $(this).removeClass('active')
        });
    });

**Comment by kticka** [comment]
Well, that popup plugin seems to be very 'delicate' :) outclick should be used on all related selectors. In your case 
```
$('.bottom-sheet-btn, .m-bottom-sheet').outclick(function() {
    $('.m-bottom-sheet').removeClass('active');
});
```
If I understood right, you want to close popup when user clicks somewhere outside popup or outside button that calls popup. In old version you had to define related objects, here you just put callback on group of selectors.

**Comment by xstortionist** [comment]
@kticka thanks for that, I will give it a shot now and report back.

I am trying to learn javascript / jquery right now, I am a complete novice but hoping to be as good as you one of these days :)

**Comment by xstortionist** [comment]
okay, that works as expected. So let me go ahead and apply that to my other buttons as well.

I really appreciate the help here and I absolutely love this plugin. Perhaps you can elaborate on how the plugin works if you have time. It would help me understand how i could achieve outclick myself. I was trying to get this to work myself with document click but I just couldn't get it working correctly.

**Comment by kticka** [comment]
Thank you :) And thnx for helping while testing everything. Well, javascript isn't my strongest side, I'm a backend developer, first version of this plugin was only for learning purposes, but when I saw that people using it, I decided refactor everything. Probably it could be better, but for now it's good. :) You should look at outclick.coffee file, it's simplier than .js. Esential thing is this line:

```
outside: (element, target) ->
    not element.is(target) and element.has(target).length is 0
```

target - element, that user clicked.
element - element that should be avoided. 

If element isn't equal to target, and if target isn't child of element, then i'm calling callback.

If write everything in pure javascript/jquery it could look smth like that:

```
$(document).on('mouseup', function(e) {
   element = $('.selector');
   if (!element.is(target) && element.has(target).length === 0) {
       alert('You have clicked outside .selector');
   }
});

```
I didn't tested this code.

**Comment by xstortionist** [comment]
No problem, I'll help out as much as possible. Everything in the links I sent you I built myself, never touched javascript til about a month ago when I started this project. I like the way coffee looks, reminds me of Jade and I'm going to convert to coffee with this framework now.

**Comment by xstortionist** [comment]
Sorry, just realized I didn't close this.

I'll be sure to check in ever once in a while.
